### ISSUE TITLE
The `wt create -b` should be able to read in JSON by default

### ISSUE THREAD

**Issue by tjanczuk** [auth0/wt-cli#55]
This is a frequent enough requirement to bundle up JSON data.

**Comment by jsierles** [comment]
auth0-node (requires its own package.json)[https://github.com/auth0/node-auth0/blob/master/src/management/index.js#L5], so can't currently be bundled with wt-cli.

**Comment by rwtombaugh** [comment]
I believe this was fixed back in April of 2016

**Comment by dbertram** [comment]
@rwtombaugh @tjanczuk @ggoodman @NotMyself  Sorry for the @mention spam, but I'm not entirely sure who's best to notify on this. I think this issue is still relevant, and appears to have possibly gotten worse (?) in the node 8 webtask environment.

## Node 4 webtask environment

In the node 4 env, running `wt create --bundle` on a project that has code like the following:

```javascript
const myRawJson = require('path/to/file.json')`
```

results in `myRawJson` containing a string rather than a parsed JS object. I've previously worked around that with the following code:

```javascript
const myJson = typeof myRawJson === 'string' ? JSON.parse(myRawJson) : myRawJson
```

The above let me run my project locally using node 8 (via `wt serve`) and still have things work properly within webtask.io's node 4 environment.

## Node 8 webtask environment

In the node 8 environment `wt create --bundle` fails with the following error:

```
./path/to/file.json
Module parse failed: Unexpected token m in JSON at position 0
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0
```

After googling around it sounds like this might be related to a webpack-based build step that's effectively double-parsing the required JSON: https://github.com/webpack/webpack/issues/6586

## Workaround

To work around this issue I've converted my `file.json` into a regular js module (i.e., `file.js` with a single `module.exports = { ... }`.

### Possibly related issue: Blocks migration of webtasks from node 4 to node 8

This issue also appears to be the reason my node 4 webtask failed to dry-run/import into the node 8 environment. With the project `require`ing a json file the `wt profile migrate` command would fail with the following error:

`...Error: getaddrinfo ENOTFOUND webtask-migrate.sandbox.auth0-extend.com webtask-migrate.sandbox.auth0-extend.com:443`

Trying to do the dry-run via webtask.io/make resulted in a similar 400 response in my JS console with the following error response:

`{code: 400, message: "unableToMigrateResponse is not defined"}`

when `POST`ing to `https://webtask-migrate.sandbox.auth0-extend.com/prod`

After removing the code that tries to `require` a json file, the dry-run/import completes successfully.
